version: '3'

services:
  db:
    build: 
      context: .
      dockerfile: database.Dockerfile
    ports:
      - "3306:3306"
    networks:
      - global
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: backend.Dockerfile
    networks:
      - global
    ports:
      - "4000:4000"
networks:
  global:
    name: global